"use client";

/**
 * app/demo-react/page.js
 * ----------------------------------------------------------------------------
 * PROOF-OF-CONCEPT for the Phase-3 direction.
 *
 * Renders CmcPage.jsx — a REAL React component our conversion tool
 * (lib/htmlToReact.js) generated from the actual captured CMC HTML prototype —
 * and layers the validated Phase-1 edit flow on top:
 *
 *     visit /demo-react?edit  →  login modal  →  inline edit mode
 *
 * No separate capture site, no URL to paste: the edit experience lives right
 * on the React version, exactly as Evan asked. Demonstrates editing text,
 * images, icons, and videos, plus duplicate / remove on repeating items.
 *
 * (POC scope: edits are live DOM mutations on the rendered component and are
 * not persisted — this exists to prove the pipeline, not to ship.)
 * ----------------------------------------------------------------------------
 */

import { memo, useEffect, useRef, useState, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import CmcPage from "./CmcPage.jsx";
import headLinks from "./headLinks.json";

// Memoized with no props → renders exactly once. That keeps our live DOM
// edits from being clobbered by React re-renders when modal/edit state changes.
const StablePage = memo(function StablePage() {
  return <CmcPage />;
});

const ICON_CHOICES = [
  "bi-star-fill", "bi-heart-fill", "bi-check-circle-fill", "bi-people-fill",
  "bi-calendar-event", "bi-geo-alt-fill", "bi-envelope-fill", "bi-telephone-fill",
  "bi-building", "bi-trophy-fill", "bi-lightbulb-fill", "bi-briefcase-fill",
];

function DemoInner() {
  const searchParams = useSearchParams();
  const editRequested = searchParams.has("edit");

  const [authed, setAuthed] = useState(false);
  const [showLogin, setShowLogin] = useState(false);
  const [email, setEmail] = useState("admin@hcdx.com");
  const [password, setPassword] = useState("demo1234");
  const [loginError, setLoginError] = useState("");
  const rootRef = useRef(null);

  const editMode = editRequested && authed;

  // Inject the prototype's own stylesheets so the converted page looks right.
  useEffect(() => {
    const added = [];
    headLinks.forEach((href) => {
      if (document.querySelector(`link[data-hcdx-css="${href}"]`)) return;
      const link = document.createElement("link");
      link.rel = "stylesheet";
      link.href = href;
      link.setAttribute("data-hcdx-css", href);
      document.head.appendChild(link);
      added.push(link);
    });
  }, []);

  // Open the login modal when ?edit is present and we're not authed yet.
  useEffect(() => {
    if (editRequested && !authed) setShowLogin(true);
  }, [editRequested, authed]);

  // Turn editing on/off over the rendered component's real DOM.
  useEffect(() => {
    if (!editMode) return;
    const root = rootRef.current;
    if (!root) return;
    const cleanup = enableEditing(root);
    return cleanup;
  }, [editMode]);

  function handleLogin(e) {
    e.preventDefault();
    if (email.trim().toLowerCase() === "admin@hcdx.com" && password === "demo1234") {
      setLoginError("");
      setShowLogin(false);
      setAuthed(true);
    } else {
      setLoginError("Incorrect email or password.");
    }
  }

  return (
    <div>
      {editMode && (
        <div style={bar}>
          <span style={{ fontWeight: 700 }}>● Edit mode</span>
          <span style={{ opacity: 0.85 }}>
            Editing the <b>converted React</b> version — click any highlighted element. Hover a card for duplicate / remove.
          </span>
          <span style={{ marginLeft: "auto", fontSize: 12, opacity: 0.7 }}>
            /demo-react — generated by lib/htmlToReact.js
          </span>
        </div>
      )}

      <div ref={rootRef} style={editMode ? { paddingTop: 4 } : undefined}>
        <StablePage />
      </div>

      {showLogin && (
        <div style={modalOverlay}>
          <form onSubmit={handleLogin} style={modalCard}>
            <div style={{ fontWeight: 700, fontSize: 18, color: "#0E2A47", marginBottom: 4 }}>
              Sign in to edit
            </div>
            <p style={{ fontSize: 13, color: "#5C6B7A", marginTop: 0, marginBottom: 18 }}>
              Editing the React version of this page.
            </p>
            <label style={lbl}>Email</label>
            <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} style={inp} />
            <label style={lbl}>Password</label>
            <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} style={{ ...inp, marginBottom: loginError ? 8 : 18 }} />
            {loginError && <p style={{ color: "#B91C1C", fontSize: 13, margin: "0 0 12px" }}>{loginError}</p>}
            <button type="submit" style={signInBtn}>Sign in &amp; edit</button>
          </form>
        </div>
      )}
    </div>
  );
}

/* ---------------- edit runtime (operates on real rendered DOM) ------------- */
function enableEditing(root) {
  const OUTLINE = "1px dashed #D97706";
  const listeners = [];
  const on = (el, ev, fn) => { el.addEventListener(ev, fn); listeners.push([el, ev, fn]); };

  root.querySelectorAll("[data-edit-id]").forEach((el) => {
    const type = el.getAttribute("data-edit-type");
    el.style.outline = OUTLINE;
    el.style.outlineOffset = "2px";
    el.style.cursor = type === "text" ? "text" : "pointer";

    if (type === "text") {
      el.setAttribute("contenteditable", "true");
    } else if (type === "image" || type === "background") {
      on(el, "mousedown", (e) => { e.preventDefault(); pickFile((url) => {
        if (type === "image") el.setAttribute("src", url);
        else el.style.backgroundImage = `url(${url})`;
      }); });
    } else if (type === "icon") {
      on(el, "mousedown", (e) => { e.preventDefault(); openIconPicker(el); });
    } else if (type === "video") {
      on(el, "mousedown", (e) => { e.preventDefault(); openVideoPicker(el); });
    }
  });

  // Duplicate / remove for repeating items via one shared floating toolbar.
  const ctl = document.createElement("div");
  ctl.style.cssText = "position:fixed;z-index:99998;display:none;gap:6px;background:#0E2A47;padding:4px;border-radius:8px;box-shadow:0 6px 20px rgba(0,0,0,.3)";
  ctl.innerHTML =
    '<button data-a="dup" style="' + ctlBtn + '">+ Duplicate</button>' +
    '<button data-a="del" style="' + ctlBtn + '">✕ Remove</button>';
  document.body.appendChild(ctl);
  let current = null;

  root.querySelectorAll("[data-edit-item]").forEach((item) => {
    on(item, "mouseenter", () => {
      current = item;
      const r = item.getBoundingClientRect();
      ctl.style.display = "flex";
      ctl.style.top = Math.max(6, r.top + 6) + "px";
      ctl.style.left = Math.max(6, r.right - 168) + "px";
    });
  });
  const hideMaybe = (e) => {
    if (ctl.contains(e.target)) return;
    if (current && current.contains(e.target)) return;
    ctl.style.display = "none";
  };
  on(document, "mousemove", (e) => {
    if (!current) return;
    if (!current.contains(e.target) && !ctl.contains(e.target)) {
      // small grace: only hide when pointer is well away
    }
  });
  ctl.querySelector('[data-a="dup"]').addEventListener("click", () => {
    if (!current) return;
    const clone = current.cloneNode(true);
    current.after(clone);
    // re-apply editing to the clone
    clone.querySelectorAll("[contenteditable]").forEach((n) => n.setAttribute("contenteditable", "true"));
  });
  ctl.querySelector('[data-a="del"]').addEventListener("click", () => {
    if (!current) return;
    current.remove();
    current = null;
    ctl.style.display = "none";
  });

  return function cleanup() {
    listeners.forEach(([el, ev, fn]) => el.removeEventListener(ev, fn));
    ctl.remove();
    root.querySelectorAll("[data-edit-id]").forEach((el) => {
      el.style.outline = ""; el.style.cursor = ""; el.removeAttribute("contenteditable");
    });
  };
}

function pickFile(cb) {
  const input = document.createElement("input");
  input.type = "file"; input.accept = "image/*";
  input.onchange = () => {
    const f = input.files && input.files[0];
    if (!f) return;
    const r = new FileReader();
    r.onload = () => cb(r.result);
    r.readAsDataURL(f);
  };
  input.click();
}

function openIconPicker(el) {
  closePopovers();
  const pop = popoverShell(el);
  pop.innerHTML = '<div style="font-weight:700;margin-bottom:8px;font-size:13px;color:#111">Pick an icon</div>' +
    '<div style="display:grid;grid-template-columns:repeat(6,1fr);gap:6px"></div>';
  const grid = pop.querySelector("div:last-child");
  ICON_CHOICES.forEach((cls) => {
    const b = document.createElement("button");
    b.className = "bi " + cls;
    b.style.cssText = "font-size:20px;padding:6px;border:1px solid #ddd;border-radius:6px;background:#fff;cursor:pointer";
    b.onclick = () => {
      const kept = (el.getAttribute("class") || "").split(/\s+/).filter((c) => c && c !== "bi" && !c.startsWith("bi-"));
      el.setAttribute("class", ["bi", cls, ...kept].join(" "));
      closePopovers();
    };
    grid.appendChild(b);
  });
  document.body.appendChild(pop);
}

function openVideoPicker(el) {
  closePopovers();
  const pop = popoverShell(el);
  const cur = el.getAttribute("src") || "";
  pop.innerHTML = '<div style="font-weight:700;margin-bottom:8px;font-size:13px;color:#111">Replace video</div>' +
    '<input type="text" value="' + cur.replace(/"/g, "&quot;") + '" style="width:260px;padding:6px;border:1px solid #ccc;border-radius:6px;font-size:12px"/>' +
    '<button style="margin-top:8px;width:100%;padding:6px;border:none;border-radius:6px;background:#1B7A43;color:#fff;cursor:pointer">Update</button>';
  const inp = pop.querySelector("input");
  pop.querySelector("button").onclick = () => { el.setAttribute("src", inp.value.trim()); closePopovers(); };
  document.body.appendChild(pop);
}

function popoverShell(el) {
  const r = el.getBoundingClientRect();
  const pop = document.createElement("div");
  pop.className = "hcdx-pop";
  pop.style.cssText = "position:fixed;z-index:99999;background:#fff;border:1px solid #d0d5dd;border-radius:10px;padding:12px;box-shadow:0 10px 30px rgba(0,0,0,.2);font-family:system-ui,sans-serif";
  pop.style.top = Math.min(window.innerHeight - 180, r.bottom + 6) + "px";
  pop.style.left = Math.min(window.innerWidth - 300, Math.max(6, r.left)) + "px";
  setTimeout(() => {
    const off = (e) => { if (!pop.contains(e.target)) { closePopovers(); document.removeEventListener("mousedown", off); } };
    document.addEventListener("mousedown", off);
  }, 0);
  return pop;
}
function closePopovers() { document.querySelectorAll(".hcdx-pop").forEach((p) => p.remove()); }

/* ---------------- styles ---------------- */
const bar = { position: "sticky", top: 0, zIndex: 9000, display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap", background: "#FEF3C7", borderBottom: "2px solid #FCD34D", color: "#92400E", padding: "9px 16px", font: "13px/1.4 system-ui, sans-serif" };
const ctlBtn = "border:none;background:#fff;color:#0E2A47;border-radius:5px;padding:4px 9px;font:600 12px system-ui;cursor:pointer";
const modalOverlay = { position: "fixed", inset: 0, background: "rgba(14,42,71,.55)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 99999, fontFamily: "system-ui, sans-serif" };
const modalCard = { background: "#fff", borderRadius: 14, padding: "30px 28px", width: "100%", maxWidth: 360, boxShadow: "0 24px 60px rgba(0,0,0,.3)" };
const lbl = { fontSize: 12.5, fontWeight: 600, color: "#16212E", display: "block", marginBottom: 5 };
const inp = { width: "100%", padding: "10px 12px", borderRadius: 8, border: "1px solid #DDE3DF", marginBottom: 16, fontSize: 14, boxSizing: "border-box" };
const signInBtn = { width: "100%", background: "#1B7A43", color: "#fff", border: "none", borderRadius: 8, padding: "12px 0", fontWeight: 600, fontSize: 15, cursor: "pointer" };

export default function DemoReactPage() {
  return (
    <Suspense fallback={<div style={{ padding: 40, fontFamily: "system-ui" }}>Loading…</div>}>
      <DemoInner />
    </Suspense>
  );
}
